### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by abhishek-mallav** [neithern/g4music#30]
Add a shuffle button next to the repeat button.

**Comment by Iron-Squid** [comment]
Seconded.

What sorts of algorithms would be necessary in order to include a shuffle function?
There are various methods one could employ to achieve this. I personally would prefer to be able to input my own custom randomness algorithm, but doing so would go against the design philosophy of GNOME, which is to keep things easy and simple for end users.
Perhaps behind an "advanced options" tab, out of the way and not cluttering the main UI, but still accessible to those that want it.


But all in all, yes please. a Shuffle function is expected of most audio players. It'd be best to add before this application becomes too popular, and it becomes a point of pointless criticism.

**Comment by neithern** [comment]
Here is a "Shuffle" mode the in sort mode menu (click the sort mode button in the title bar).
It is a simple random algorithm to shuffle the music list directly, the benefits are:
- You can see what will be played next
- No music will be played over and over again
- You can go forward and backward without change the order.
