### ISSUE TITLE
Strange playlist toggle

### ISSUE THREAD

**Issue by daudix-UFO** [neithern/g4music#5]
Amberol has player as a main page, in "square mode" when playlist and player fits, there is button to toggle playlist, G4Music lost this functionaliy after adding back button, and gesture now broken

https://user-images.githubusercontent.com/77155297/174322018-ddb8cc68-7e59-4a22-afb6-e18db9c16fcd.mp4

**Comment by neithern** [comment]
G4Music now use [Adw.Leaflet](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/adaptive-layouts.html#leaflet) instead of [Adw.Flap](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/adaptive-layouts.html#flap) to adapt the different size of screen, it is better for phone screen. 
About the gesture, I think it is a bug/issue of libadwaita, they should make "swap-to-close" always works.
